In [1]:
import numpy as np

In [2]:
A = np.array([[0.8, 0.1, 0.1], 
              [0.2, 0.7, 0.1], 
              [0.1, 0.3, 0.6]])

C = np.array([0.6, 0.2, 0.2])

B = np.array([[0.7, 0.0, 0.3], 
              [0.1, 0.9, 0.0], 
              [0.0, 0.2, 0.8]])
O = np.array([0, 2, 0, 2, 2, 1]).astype(np.int32)



def viterbi_log(A, C, B, O):
    """Viterbi algorithm (log variant) for solving the uncovering problem

    Notebook: C5/C5S3_Viterbi.ipynb

    Args:
        A (np.ndarray): State transition probability matrix of dimension I x I
        C (np.ndarray): Initial state distribution  of dimension I
        B (np.ndarray): Output probability matrix of dimension I x K
        O (np.ndarray): Observation sequence of length N

    Returns:
        S_opt (np.ndarray): Optimal state sequence of length N
        D_log (np.ndarray): Accumulated log probability matrix
        E (np.ndarray): Backtracking matrix
    """
    I = A.shape[0]    # Number of states
    N = len(O)  # Length of observation sequence
    tiny = np.finfo(0.).tiny
    A_log = A
    C_log = C
    B_log = B
    #print(B)
    print("C", C_log,"\n",  B_log)

    # Initialize D and E matrices
    D_log = np.zeros((I, N))
    E = np.zeros((I, N-1)).astype(np.int32)
    D_log[:, 0] = C_log + B_log[:, O[0]]
    print(D_log, "Emisison at Obersation o:", B_log[:, O[0]] )

    # Compute D and E in a nested loop
    for n in range(1, N):
        for i in range(I):
            print(n, i)
            temp_sum = A_log[:, i] + D_log[:, n-1]
            D_log[i, n] = np.max(temp_sum) + B_log[i, O[n]]
            E[i, n-1] = np.argmax(temp_sum)

    # Backtracking
    S_opt = np.zeros(N).astype(np.int32)
    S_opt[-1] = np.argmax(D_log[:, -1])
    for n in range(N-2, -1, -1):
        S_opt[n] = E[int(S_opt[n+1]), n]

    return S_opt, D_log, E

# Apply Viterbi algorithm (log variant)
S_opt, D_log, E = viterbi_log(A, C, B, O)

print('Observation sequence:   O = ', O)
print('Optimal state sequence: S = ', S_opt)
np.set_printoptions(formatter={'float': "{: 7.2f}".format})
print('D_log =', D_log, sep='\n')
np.set_printoptions(formatter={'float': "{: 7.4f}".format})
print('exp(D_log) =', np.exp(D_log), sep='\n')
np.set_printoptions(formatter={'float': "{: 7.0f}".format})
print('E =', E, sep='\n')

C [0.6 0.2 0.2] 
 [[0.7 0.  0.3]
 [0.1 0.9 0. ]
 [0.  0.2 0.8]]
[[1.3 0.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.  0.  0. ]] Emisison at Obersation o: [0.7 0.1 0. ]
1 0
1 1
1 2
2 0
2 1
2 2
3 0
3 1
3 2
4 0
4 1
4 2
5 0
5 1
5 2
Observation sequence:   O =  [0 2 0 2 2 1]
Optimal state sequence: S =  [0 0 0 2 2 1]
D_log =
[[   1.30    2.40    3.90    5.00    6.10    6.90]
 [   0.30    1.40    2.60    4.00    5.10    7.40]
 [   0.20    2.20    2.80    4.80    6.20    7.00]]
exp(D_log) =
[[ 3.6693  11.0232  49.4024  148.4132  445.8578  992.2747]
 [ 1.3499  4.0552  13.4637  54.5982  164.0219  1635.9844]
 [ 1.2214  9.0250  16.4446  121.5104  492.7490  1096.6332]]
E =
[[0 0 0 0 0]
 [0 2 0 2 2]
 [0 2 0 2 2]]
